language: android
jdk: oraclejdk8
sudo: required
env:
  global:
  - ANDROID_API=26
  - EMULATOR_API=21
  - ANDROID_BUILD_TOOLS=26.0.2
  - ADB_INSTALL_TIMEOUT=5
  - secure: QTFEpXIf2vdpflVcR7WWiBUwehqAjTlKo7Nh/rk93SpTpqbBsxlyCiMcP3fAXblKmcDnwU3xFngaeBg/8oRNcqDOXo2rJGjGhe4vep68Q6qy0eWnBnpScvEvJ2P2SrOb/S58LhnAt8O5R5CiDlEm0Gca3I6dfpOMTjjPbKQUHHW3Or1hyMB7N8/+b9thn11LQ+3cN6dILm7ebTAE6KrS2GSgRhwegbGZ7GSB+XbWiq3nrV1pEo86DQi4ogYypNP5OP1U20jndaa3bovl0zDSAABVWzE7kvzOd+XwZ0MtdAL+os3iLlsF2+5QzzMZb/u21IyoDCYpGs3MK3ws4jWfa4NIREiDh/7DLB3jVR/Ewetp1cJtNExtTuhbk+6UrOn8kkmYUo1K/a2G/HEKGu68YYNFe7QugnGAF+2JnQFAW8waYareDL+jvcFObXxmFp77HBDx7xjCy1xE/AJkRL9iFcxbmhjGx0v7PQ5m/Z5z7cue8Aqb+oCgReXc1ghm7OEz8galJmJ6W3Z7Uou3vBdg2bsnjMC3eD7NEfrhZZiIRuCqwRXXw6RX2W7Sw8n4Aes7wnmemePzO5FpIEzVH/5/5V5CEQ67g9Q3yF4K1T1lEOq8e3Oq1BKhci4a0auWcEk3T/laDNKJh7gsMsxX7qm3trzn9gq0Ge1KMXEmr7uLm6k=
  - secure: S1d4JlvqsBIfFhTPRefoZytj2IuMdS9iZwoehlOCRl8wRerj6HAk/Prn0HXUTfoCOCVQ4x/+f/Mazq8prfhNSt2DKU4YOhcAToTCQn6stqtyyrHrvxwapKsSsKDK5sZ+wPLqczF3UtQi1s/hcTKZT8gNplUO66LkcpCO7DkkXS03N7EMVFTTLXvR+xb5WkPZjhxxjOnRpwN8vKNAAJ9pm3hTrTMgawoQI/CZ8vkEpWvwS/Av5TeumzXcN+grphwPvSF6DGjf/qR5Zh6OyliUgx6DymRMPU4VYhl6yzYafSSd7wujJY8JcE3Pv14NdlXZhuLGqITMvnRw0LJs+ijD0bI4bay37FCaLZksuUt45HGcSBkkLRlNc89vZWkv7CTnnKYdrTQtWt/3Mxvhp9xrRtqMBVzRdqQFkNoYk2qvZLaHpCq+KxIykJFKEh+NYsN8SNWbt2RauYC6nE12AgcIcFR89aStZeOAXKJ/lL/r3yY5xliy0VVjMK5eobbqqALr4fJGORA7nA91QzZrJZrPVo+QjwAX29e1F0GtmI8FSnbJz27gOj9Djgt2InA2tuIHJNeXThgMYBmyKDbUWuPPQ64J3E4YRjkQj3ORbRXmfQ6tRorZouLlYoc3Wc9HefsWBR/utdOEIYOoMG+SRVQFzY9uZbeBm8vEO5CZFOJwVaI=
android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - android-$EMULATOR_API
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-$ANDROID_API
  - sys-img-armeabi-v7a-android-$EMULATOR_API
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_script:
- echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
- emulator -avd test -no-audio -no-window &
- android-wait-for-emulator
before_install:
- openssl aes-256-cbc -K $encrypted_34598bd135b1_key -iv $encrypted_34598bd135b1_iv
  -in pgyer.jks.enc -out pgyer.jks -d
- cd $TRAVIS_BUILD_DIR
- wget -c https://raw.githubusercontent.com/Pgyer/TravisFile/master/pgyer_upload.sh
  -O pgyer_upload.sh
- chmod +x pgyer_upload.sh
script:
- "./gradlew assembleRelease"
after_success:
- cp $TRAVIS_BUILD_DIR/pgyer.jks $HOME
- cd $TRAVIS_BUILD_DIR/app/build/outputs/apk/release
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/pgyer.jks
  -storepass $storepass -keypass $keypass app-release-unsigned.apk pgyer
- jarsigner -verify app-release-unsigned.apk
- "${ANDROID_HOME}/build-tools/26.0.2/zipalign -v 4 app-release-unsigned.apk yourapp.apk"
after_script:
- set -e
- $TRAVIS_BUILD_DIR/pgyer_upload.sh "${TRAVIS_BUILD_DIR}/app/build/outputs/apk/release/yourapp.apk"
  "e2dc422e5050e62627308e84e370679e"
- rm $TRAVIS_BUILD_DIR/pgyer_upload.sh
